
import { PlaceHolderImages, ImagePlaceholder } from "@/lib/placeholder-images";

export type PortfolioItemType = {
  id: string;
  title: string;
  category: string; // "Giro"
  sector: string; // "Sector"
  image?: ImagePlaceholder;
  description: string;
  services: string[];
  website?: string;
  client: string;
  challenge: string;
  solution: string;
  parallaxImages?: {
    laptop: string;
    phone: string;
  };
};

const placeholderImages = [
  PlaceHolderImages.find(img => img.id === 'portfolio-web-ficc'),
  PlaceHolderImages.find(img => img.id === 'portfolio-web-dfac'),
  PlaceHolderImages.find(img => img.id === 'portfolio-web-polar')
].filter(Boolean) as ImagePlaceholder[];

let imageCounter = 0;

const getNextImage = () => {
  const image = placeholderImages[imageCounter];
  imageCounter = (imageCounter + 1) % placeholderImages.length;
  return image;
}

export const portfolioItems: PortfolioItemType[] = [
  {
    "id": "additum-org",
    "title": "Additum",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://additum.org",
    "client": "Additum",
    "image": getNextImage(),
    "description": "Plataforma de servicios profesionales.",
    "challenge": "Crear una presencia digital profesional.",
    "solution": "Se desarrolló un sitio web corporativo que refleja la experiencia y profesionalismo de la firma.",
    "services": ["Diseño y Desarrollo Web", "Diseño UX/UI"]
  },
  {
    "id": "adventuresgi-com",
    "title": "Adventures GI",
    "category": "Connective",
    "sector": "Actividades recreativas",
    "website": "https://adventuresgi.com",
    "client": "Adventures GI",
    "image": getNextImage(),
    "description": "Sitio para empresa de actividades recreativas.",
    "challenge": "Transmitir la emoción y aventura de las experiencias ofrecidas.",
    "solution": "Un diseño visualmente dinámico con videos e imágenes de alta calidad para atraer a los buscadores de aventuras.",
    "services": ["Diseño y Desarrollo Web", "Integración Multimedia"]
  },
  {
    "id": "festivaldecineloscabos-mx",
    "title": "Festival de Cine Los Cabos",
    "category": "Connective",
    "sector": "Eventos",
    "website": "https://festivaldecineloscabos.mx",
    "client": "Festival de Cine Los Cabos",
    "image": getNextImage(),
    "description": "Sitio oficial para el festival internacional de cine.",
    "challenge": "Gestionar un alto volumen de información: películas, horarios, jurado, y venta de boletos.",
    "solution": "Una plataforma robusta con una base de datos centralizada, permitiendo actualizaciones en tiempo real y una experiencia de usuario fluida.",
    "services": ["Diseño y Desarrollo Web", "Gestión de Contenidos para Eventos"]
  },
  {
    "id": "buffaloribs-info",
    "title": "Buffalo Ribs",
    "category": "Landing",
    "sector": "Restaurante",
    "website": "https://buffaloribs.info",
    "client": "Buffalo Ribs",
    "image": getNextImage(),
    "description": "Landing page para restaurante.",
    "challenge": "Captar la atención del cliente y facilitar la reservación o pedido en línea.",
    "solution": "Una landing page de una sola página, optimizada para móviles, con menú visible y botones de llamado a la acción claros.",
    "services": ["Diseño de Landing Page", "Optimización de Conversión"]
  },
  {
    "id": "ixagaleather-com-mx",
    "title": "Ixaga Leather",
    "category": "E-commerce",
    "sector": "Ropa y Calzado",
    "website": "https://ixagaleather.com.mx",
    "client": "Ixaga Leather",
    "image": getNextImage(),
    "description": "Tienda en línea de productos de piel.",
    "challenge": "Mostrar la calidad artesanal del producto y ofrecer una experiencia de compra segura.",
    "solution": "Una plataforma de e-commerce con fotografía de producto de alta calidad, pasarelas de pago seguras y una navegación intuitiva.",
    "services": ["Desarrollo de E-commerce", "Fotografía de Producto"]
  },
  {
    "id": "paologourmet-com-mx",
    "title": "Paolo Gourmet",
    "category": "Connective",
    "sector": "Restaurante",
    "website": "https://paologourmet.com.mx",
    "client": "Paolo Gourmet",
    "image": getNextImage(),
    "description": "Sitio para negocio de tablas de queso y productos gourmet.",
    "challenge": "Crear una experiencia visual premium que refleje la calidad del producto.",
    "solution": "Diseño elegante con enfoque en la fotografía de alimentos y un sistema de pedidos personalizado para eventos.",
    "services": ["Diseño y Desarrollo Web", "Catálogo Digital"]
  },
  {
    "id": "epicrides-com-mx",
    "title": "Epic Rides",
    "category": "E-commerce",
    "sector": "Eventos",
    "website": "https://epicrides.com.mx",
    "client": "Epic Rides",
    "image": getNextImage(),
    "description": "Plataforma de e-commerce para eventos y experiencias.",
    "challenge": "Facilitar la compra de boletos y la gestión de participantes para diversos eventos.",
    "solution": "Una plataforma de e-commerce con sistema de ticketing integrado y perfiles de usuario para gestionar sus compras.",
    "services": ["Desarrollo de E-commerce", "Sistema de Ticketing"]
  },
  {
    "id": "ciemsacv-com",
    "title": "Ciemsa CV",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://ciemsacv.com",
    "client": "Ciemsa CV",
    "image": getNextImage(),
    "description": "Sitio corporativo de servicios profesionales.",
    "challenge": "Proyectar confianza y profesionalismo en un sector competitivo.",
    "solution": "Un diseño web sobrio y profesional, con casos de estudio y testimonios para construir credibilidad.",
    "services": ["Diseño y Desarrollo Web", "Marketing de Contenidos"]
  },
  {
    "id": "simtex-com-mx",
    "title": "Simtex",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://simtex.com.mx",
    "client": "Simtex",
    "image": getNextImage(),
    "description": "Plataforma para empresa de servicios profesionales.",
    "challenge": "Diferenciarse en el mercado y generar leads de calidad.",
    "solution": "Sitio web optimizado para SEO con un blog de autoridad en la industria para atraer tráfico cualificado.",
    "services": ["Diseño y Desarrollo Web", "SEO y Marketing de Contenidos"]
  },
  {
    "id": "latribuenmexico-com",
    "title": "La Tribu en México",
    "category": "Landing",
    "sector": "Actividades recreativas",
    "website": "https://latribuenmexico.com",
    "client": "La Tribu en México",
    "image": getNextImage(),
    "description": "Landing page para evento de actividades recreativas.",
    "challenge": "Generar inscripciones y comunicar la información del evento de forma clara y concisa.",
    "solution": "Landing page de alto impacto con un formulario de inscripción visible y toda la información clave del evento.",
    "services": ["Diseño de Landing Page", "Formularios de Captación"]
  },
  {
    "id": "detectoresyextintorescontraicendio-com",
    "title": "Detectores y Extintores",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://detectoresyextintorescontraicendio.com",
    "client": "Detectores y Extintores Contra Incendio",
    "image": getNextImage(),
    "description": "Sitio web para empresa de seguridad contra incendios.",
    "challenge": "Generar confianza en un servicio crítico para la seguridad.",
    "solution": "Un sitio claro, profesional, que destaca certificaciones y testimonios para construir credibilidad.",
    "services": ["Diseño y Desarrollo Web", "Estrategia de Contenido"]
  },
  {
    "id": "laminadeoro-com",
    "title": "Lámina de Oro",
    "category": "E-commerce",
    "sector": "Otros",
    "website": "https://laminadeoro.com",
    "client": "Lámina de Oro",
    "image": getNextImage(),
    "description": "E-commerce de productos especializados.",
    "challenge": "Vender un producto de nicho a una audiencia específica.",
    "solution": "Plataforma de e-commerce con contenido educativo que explica los usos y beneficios del producto, atrayendo a la audiencia correcta.",
    "services": ["Desarrollo de E-commerce", "Marketing de Contenidos"]
  },
  {
    "id": "cenotesanisidro-com",
    "title": "Cenote San Isidro",
    "category": "E-commerce",
    "sector": "Actividades recreativas",
    "website": "https://cenotesanisidro.com",
    "client": "Cenote San Isidro",
    "image": getNextImage(),
    "description": "Sitio de e-commerce para un destino turístico.",
    "challenge": "Vender boletos y paquetes turísticos en línea.",
    "solution": "Plataforma de e-commerce visualmente atractiva con un sistema de reservas integrado.",
    "services": ["Desarrollo de E-commerce", "Sistema de Reservas"]
  },
  {
    "id": "mbi-inversiones-com",
    "title": "MBI Inversiones",
    "category": "Connective",
    "sector": "Inmobiliaria",
    "website": "https://mbi-inversiones.com",
    "client": "MBI Inversiones",
    "image": getNextImage(),
    "description": "Sitio web para firma de inversiones inmobiliarias.",
    "challenge": "Proyectar solidez y confianza para atraer a inversores.",
    "solution": "Un sitio web corporativo con un diseño premium, mostrando portafolio de proyectos y datos de retorno de inversión.",
    "services": ["Diseño y Desarrollo Web", "Estrategia de Contenido Financiero"]
  },
  {
    "id": "auditoriosantiago-com",
    "title": "Auditorio Santiago",
    "category": "Connective",
    "sector": "Eventos",
    "website": "https://auditoriosantiago.com",
    "client": "Auditorio Santiago",
    "image": getNextImage(),
    "description": "Plataforma digital para un auditorio de eventos.",
    "challenge": "Gestionar el calendario de eventos y facilitar la compra de boletos.",
    "solution": "Sitio web con un calendario de eventos interactivo y una integración fluida con una plataforma de ticketing.",
    "services": ["Diseño y Desarrollo Web", "Integración de Ticketing"]
  },
  {
    "id": "buscoalhombredemivida-com",
    "title": "Busco al Hombre de mi Vida",
    "category": "Connective",
    "sector": "Eventos",
    "website": "https://buscoalhombredemivida.com",
    "client": "Producción de Teatro",
    "image": getNextImage(),
    "description": "Sitio web para obra de teatro.",
    "challenge": "Generar interés y vender boletos para la producción teatral.",
    "solution": "Un sitio web temático y atractivo con videos, sinopsis, y un claro llamado a la acción para comprar boletos.",
    "services": ["Diseño y Desarrollo Web", "Marketing para Eventos"]
  },
  {
    "id": "flotillassegurascrm-mx",
    "title": "Flotillas Seguras CRM",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://flotillassegurascrm.mx",
    "client": "Flotillas Seguras CRM",
    "image": getNextImage(),
    "description": "Sitio para un CRM especializado en la gestión de flotillas.",
    "challenge": "Explicar las características de un software B2B complejo de manera sencilla.",
    "solution": "Un sitio web centrado en los beneficios y casos de uso, con demos y tutoriales para educar al prospecto.",
    "services": ["Diseño y Desarrollo Web", "Marketing de Producto SaaS"]
  },
  {
    "id": "electrica-sanmiguel-com",
    "title": "Eléctrica San Miguel",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://electrica-sanmiguel.com",
    "client": "Eléctrica San Miguel",
    "image": getNextImage(),
    "description": "Sitio para distribuidor de material eléctrico.",
    "challenge": "Digitalizar un catálogo extenso y facilitar las cotizaciones B2B.",
    "solution": "Catálogo en línea con buscador y un sistema de solicitud de cotización simplificado para clientes mayoristas.",
    "services": ["Diseño y Desarrollo Web", "Catálogo Digital B2B"]
  },
  {
    "id": "plantforst-com",
    "title": "Plantforst",
    "category": "E-commerce",
    "sector": "Otros",
    "website": "https://plantforst.com",
    "client": "Plantforst",
    "image": getNextImage(),
    "description": "E-commerce de plantas y productos de jardinería.",
    "challenge": "Crear una comunidad en torno a la marca y vender online.",
    "solution": "Una tienda online con un blog de consejos de jardinería y una fuerte integración con Instagram para fomentar la comunidad.",
    "services": ["Desarrollo de E-commerce", "Marketing de Contenidos"]
  },
  {
    "id": "lasdeliciasdelcampo-com",
    "title": "Las Delicias del Campo",
    "category": "E-commerce",
    "sector": "Restaurante",
    "website": "https://lasdeliciasdelcampo.com",
    "client": "Las Delicias del Campo",
    "image": getNextImage(),
    "description": "E-commerce para restaurante con delivery.",
    "challenge": "Ofrecer una experiencia de pedido en línea fluida y rápida.",
    "solution": "Plataforma de e-commerce optimizada para móviles con un menú interactivo y sistema de pedidos en línea integrado.",
    "services": ["Desarrollo de E-commerce", "Sistema de Pedidos Online"]
  },
  {
    "id": "asrfloraldesing-com",
    "title": "ASR Floral Design",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://asrfloraldesing.com",
    "client": "ASR Floral Design",
    "image": getNextImage(),
    "description": "Sitio web para diseñadora floral.",
    "challenge": "Mostrar la creatividad y arte del diseño floral.",
    "solution": "Un sitio altamente visual, con un portafolio de imágenes de alta calidad y un blog sobre tendencias florales.",
    "services": ["Diseño y Desarrollo Web", "Portafolio Digital"]
  },
  {
    "id": "mawsoluciones-com",
    "title": "MAW Soluciones",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://mawsoluciones.com",
    "client": "MAW Soluciones",
    "image": getNextImage(),
    "description": "Nuestro propio sitio de agencia de marketing digital.",
    "challenge": "Demostrar nuestra propia experiencia y generar leads para nuestros servicios.",
    "solution": "Un sitio que funciona como nuestro mejor caso de estudio, con un portafolio detallado, blog de autoridad y CTAs claros.",
    "services": ["Diseño y Desarrollo Web", "Marketing de Contenidos", "Generación de Leads"]
  },
  {
    "id": "luhotza-com",
    "title": "Luhotza",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://luhotza.com",
    "client": "Luhotza",
    "image": getNextImage(),
    "description": "Sitio para firma de servicios profesionales.",
    "challenge": "Establecer una presencia digital creíble y profesional.",
    "solution": "Diseño web corporativo enfocado en la claridad, la experiencia del equipo y los casos de éxito.",
    "services": ["Diseño y Desarrollo Web", "Estrategia de Marca Digital"]
  },
  {
    "id": "audifonosdeasa-com",
    "title": "Audífonos DEASA",
    "category": "Connective",
    "sector": "Medico",
    "website": "https://audifonosdeasa.com",
    "client": "Audífonos DEASA",
    "image": getNextImage(),
    "description": "Sitio web para centro auditivo.",
    "challenge": "Generar confianza y educar a los pacientes sobre soluciones auditivas.",
    "solution": "Un sitio web informativo y accesible, con testimonios de pacientes y recursos educativos claros.",
    "services": ["Diseño y Desarrollo Web", "Marketing de Contenidos de Salud"]
  },
  {
    "id": "propertytraders-online",
    "title": "Property Traders",
    "category": "Connective",
    "sector": "Inmobiliaria",
    "website": "https://propertytraders.online/",
    "client": "Property Traders",
    "image": getNextImage(),
    "description": "Plataforma para el sector inmobiliario.",
    "challenge": "Facilitar la búsqueda y el listado de propiedades.",
    "solution": "Un portal con un potente buscador con filtros, mapas interactivos y perfiles detallados de propiedades.",
    "services": ["Desarrollo de Portal Inmobiliario", "Integración de Mapas"]
  },
  {
    "id": "cirujano-maxilofacial-com",
    "title": "Cirujano Maxilofacial",
    "category": "Connective",
    "sector": "Medico",
    "website": "https://cirujano-maxilofacial.com",
    "client": "Dr. Maxilofacial",
    "image": getNextImage(),
    "description": "Sitio web para cirujano maxilofacial.",
    "challenge": "Atraer pacientes y educar sobre procedimientos complejos de manera sencilla y tranquilizadora.",
    "solution": "Un sitio web profesional y empático, con explicaciones claras de los procedimientos, testimonios y un sistema de agendamiento de citas.",
    "services": ["Diseño y Desarrollo Web", "Marketing para Sector Salud"]
  },
  {
    "id": "suministroshebe-com",
    "title": "Suministros Hebe",
    "category": "E-commerce",
    "sector": "Sector industrial",
    "website": "https://suministroshebe.com",
    "client": "Suministros Hebe",
    "image": getNextImage(),
    "description": "E-commerce B2B de suministros industriales.",
    "challenge": "Gestionar un catálogo de productos técnicos y facilitar la compra a clientes empresariales.",
    "solution": "Plataforma de e-commerce con acceso por niveles de usuario, precios personalizados y opciones de compra al por mayor.",
    "services": ["Desarrollo de E-commerce B2B", "Gestión de Catálogo Complejo"]
  },
  {
    "id": "cursosdeinglesbrooklyn-com",
    "title": "Cursos de Inglés Brooklyn",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://cursosdeinglesbrooklyn.com",
    "client": "Cursos de Inglés Brooklyn",
    "image": getNextImage(),
    "description": "Sitio para academia de inglés.",
    "challenge": "Atraer nuevos estudiantes y facilitar el proceso de inscripción.",
    "solution": "Sitio web dinámico con información sobre los cursos, niveles, y un sistema de inscripción y pago en línea.",
    "services": ["Diseño y Desarrollo Web", "Sistema de Inscripción Online"]
  },
  {
    "id": "pisosepoxicoslexfor-com",
    "title": "Pisos Epóxicos Lexfor",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://pisosepoxicoslexfor.com",
    "client": "Pisos Epóxicos Lexfor",
    "image": getNextImage(),
    "description": "Sitio web para empresa de pisos industriales.",
    "challenge": "Mostrar la durabilidad y calidad técnica de los productos.",
    "solution": "Un sitio con un portafolio de proyectos robusto, mostrando el antes y después y especificaciones técnicas detalladas.",
    "services": ["Diseño y Desarrollo Web", "Portafolio de Proyectos B2B"]
  },
  {
    "id": "traktobuss-com",
    "title": "Traktobuss",
    "category": "E-commerce",
    "sector": "Sector industrial",
    "website": "https://traktobuss.com",
    "client": "Traktobuss",
    "image": getNextImage(),
    "description": "E-commerce de refacciones para autobuses y camiones.",
    "challenge": "Manejar un inventario de miles de piezas con compatibilidades complejas.",
    "solution": "Una plataforma de e-commerce con un buscador por número de parte, marca y modelo para asegurar la compra correcta.",
    "services": ["Desarrollo de E-commerce", "Buscador Avanzado de Productos"]
  },
  {
    "id": "atleticamd-com",
    "title": "Atletica MD",
    "category": "Connective",
    "sector": "Medico",
    "website": "https://atleticamd.com",
    "client": "Atletica MD",
    "image": getNextImage(),
    "description": "Sitio para clínica de medicina deportiva.",
    "challenge": "Posicionarse como expertos en el tratamiento de atletas.",
    "solution": "Un sitio con un blog de autoridad sobre lesiones deportivas, testimonios de atletas y un sistema de agendamiento de citas.",
    "services": ["Diseño y Desarrollo Web", "Marketing de Contenidos para Salud"]
  },
  {
    "id": "elconejo-com-mx",
    "title": "El Conejo",
    "category": "E-commerce",
    "sector": "Sector industrial",
    "website": "https://elconejo.com.mx",
    "client": "El Conejo",
    "image": getNextImage(),
    "description": "E-commerce de herramientas y maquinaria.",
    "challenge": "Vender productos de alto valor y especificaciones técnicas en línea.",
    "solution": "Fichas de producto detalladas con especificaciones, videos de uso y un chat en vivo para asesoría técnica.",
    "services": ["Desarrollo de E-commerce", "Fichas de Producto Detalladas"]
  },
  {
    "id": "kohui-com-mx",
    "title": "Kohui",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://kohui.com.mx",
    "client": "Kohui",
    "image": getNextImage(),
    "description": "Sitio para consultoría de servicios profesionales.",
    "challenge": "Comunicar una propuesta de valor compleja de forma clara.",
    "solution": "Un sitio estructurado en torno a los beneficios para el cliente, con casos de estudio que demuestran el impacto real.",
    "services": ["Diseño y Desarrollo Web", "Estrategia de Contenido B2B"]
  },
  {
    "id": "maestrodelmedia-com",
    "title": "Maestro del Media",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://maestrodelmedia.com",
    "client": "Maestro del Media",
    "image": getNextImage(),
    "description": "Plataforma de servicios de marketing y medios.",
    "challenge": "Destacar en un mercado de agencias de marketing muy competitivo.",
    "solution": "Un portafolio dinámico que muestra resultados concretos y un blog que establece a la agencia como líder de opinión.",
    "services": ["Diseño y Desarrollo Web", "Marketing de Agencia"]
  },
  {
    "id": "psepowerbatteries-com",
    "title": "PSE Power Batteries",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://psepowerbatteries.com",
    "client": "PSE Power Batteries",
    "image": getNextImage(),
    "description": "Sitio web para fabricante de baterías industriales.",
    "challenge": "Mostrar la superioridad técnica y confiabilidad de los productos.",
    "solution": "Un sitio web con fichas técnicas descargables, certificaciones a la vista y un comparador de productos.",
    "services": ["Diseño y Desarrollo Web", "Catálogo Técnico de Productos"]
  },
  {
    "id": "caficon-info",
    "title": "Caficon",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://caficon.info",
    "client": "Caficon",
    "image": getNextImage(),
    "description": "Sitio para consultoría financiera y contable.",
    "challenge": "Generar confianza en un área sensible como las finanzas.",
    "solution": "Diseño profesional y sobrio, con recursos gratuitos (calculadoras, guías fiscales) para demostrar expertise y captar leads.",
    "services": ["Diseño y Desarrollo Web", "Generación de Leads B2B"]
  },
  {
    "id": "distribuidoradepvc-com-mx",
    "title": "Distribuidora de PVC",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://distribuidoradepvc.com.mx",
    "client": "Distribuidora de PVC",
    "image": getNextImage(),
    "description": "Plataforma para distribuidor de materiales de PVC.",
    "challenge": "Facilitar la cotización para proyectos de construcción a gran escala.",
    "solution": "Un catálogo digital con un sistema de 'carrito de cotización' que permite a los clientes armar su pedido y solicitar un presupuesto.",
    "services": ["Diseño y Desarrollo Web", "Sistema de Cotización Online"]
  },
  {
    "id": "papierwaren-com-mx",
    "title": "Papierwaren",
    "category": "Connective",
    "sector": "Active",
    "website": "https://papierwaren.com.mx",
    "client": "Papierwaren",
    "image": getNextImage(),
    "description": "Sitio para marca de papelería y diseño.",
    "challenge": "Transmitir una estética de marca única y creativa.",
    "solution": "Un diseño web minimalista y elegante, que funciona como un portafolio de arte y dirige a los puntos de venta.",
    "services": ["Diseño y Desarrollo Web", "Portafolio de Marca"]
  },
  {
    "id": "bpsolutions-com-mx",
    "title": "BP Solutions",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://bpsolutions.com.mx",
    "client": "BP Solutions",
    "image": getNextImage(),
    "description": "Sitio para empresa de soluciones empresariales.",
    "challenge": "Articular un portafolio de servicios diverso bajo una marca unificada.",
    "solution": "Una arquitectura de información clara que guía a cada tipo de cliente a la solución que necesita, con casos de estudio relevantes.",
    "services": ["Diseño y Desarrollo Web", "Arquitectura de la Información"]
  },
  {
    "id": "bhdmx-com",
    "title": "BHDMX",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://www.bhdmx.com/",
    "client": "BHDMX",
    "image": getNextImage(),
    "description": "Plataforma para servicios profesionales.",
    "challenge": "Crear una presencia digital moderna y confiable.",
    "solution": "Un sitio web con un diseño limpio y corporativo, enfocado en la experiencia y testimonios de clientes.",
    "services": ["Diseño y Desarrollo Web", "Diseño UX/UI"]
  },
  {
    "id": "bove-com-mx",
    "title": "Bove",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://bove.com.mx/",
    "client": "Bove",
    "image": getNextImage(),
    "description": "Sitio para empresa del sector industrial.",
    "challenge": "Digitalizar la presencia de una marca consolidada en la industria.",
    "solution": "Un sitio web robusto que muestra la capacidad de producción, certificaciones de calidad y proyectos emblemáticos.",
    "services": ["Diseño y Desarrollo Web", "Comunicación Corporativa"]
  },
  {
    "id": "polarautopartes-com",
    "title": "Polar Autopartes",
    "category": "E-commerce",
    "sector": "Sector industrial",
    "website": "https://www.polarautopartes.com/",
    "client": "Polar Autopartes",
    "image": getNextImage(),
    "description": "E-commerce de refacciones para sistemas de enfriamiento automotriz.",
    "challenge": "Crear un buscador de compatibilidad de piezas por marca, modelo y año.",
    "solution": "Una plataforma de e-commerce con un motor de búsqueda avanzado para garantizar que los clientes encuentren la pieza exacta.",
    "services": ["Desarrollo de E-commerce", "Buscador de Productos Avanzado"]
  },
  {
    "id": "core31-com-mx",
    "title": "CORE 31",
    "category": "Connective",
    "sector": "Inmobiliaria",
    "website": "https://core31.com.mx",
    "client": "CORE 31",
    "image": getNextImage(),
    "description": "Sitio para box de Wod & Fitness.",
    "challenge": "Capturar la energía y comunidad del lugar en un sitio web.",
    "solution": "Un diseño oscuro y enérgico, con videos de acción y un horario de clases interactivo.",
    "services": ["Diseño y Desarrollo Web", "Diseño Inmersivo"]
  },
  {
    "id": "concamin-comenor-org-mx",
    "title": "Concamin Comenor",
    "category": "E-commerce",
    "sector": "Servicios Profesionales",
    "website": "https://concamin.comenor.org.mx/",
    "client": "Concamin Comenor",
    "image": getNextImage(),
    "description": "Plataforma de servicios profesionales con opción de pago.",
    "challenge": "Facilitar la inscripción y pago a eventos o certificaciones.",
    "solution": "Un sitio con un área de miembros y una pasarela de pago para gestionar inscripciones y renovaciones.",
    "services": ["Desarrollo de E-commerce", "Área de Miembros"]
  },
  {
    "id": "cuestiondepolemica-com",
    "title": "Cuestión de Polémica",
    "category": "Connective",
    "sector": "Noticias",
    "website": "https://www.cuestiondepolemica.com/",
    "client": "Cuestión de Polémica",
    "image": getNextImage(),
    "description": "Portal de noticias y opinión.",
    "challenge": "Manejar un alto volumen de publicaciones y optimizar la velocidad de carga para una gran audiencia.",
    "solution": "Un sitio basado en un CMS optimizado para medios, con carga diferida de imágenes y una arquitectura que soporta picos de tráfico.",
    "services": ["Desarrollo de Portal de Noticias", "Optimización de Rendimiento"]
  },
  {
    "id": "valor-compartido-com",
    "title": "Valor Compartido",
    "category": "Connective",
    "sector": "Noticias",
    "website": "https://valor-compartido.com/",
    "client": "Valor Compartido",
    "image": getNextImage(),
    "description": "Portal de noticias enfocado en sostenibilidad y RSE.",
    "challenge": "Crear una plataforma editorial que sea fácil de gestionar para un equipo de periodistas.",
    "solution": "Un CMS personalizado (WordPress) con roles de usuario, flujo de aprobación de contenido y una interfaz de publicación intuitiva.",
    "services": ["Desarrollo de Portal de Noticias", "Implementación de CMS a medida"]
  },
  {
    "id": "niu-coliving-com",
    "title": "Niu Coliving",
    "category": "Connective",
    "sector": "Inmobiliaria",
    "website": "https://niu-coliving.com/es/",
    "client": "Niu Coliving",
    "image": getNextImage(),
    "description": "Sitio web para empresa de coliving.",
    "challenge": "Vender un estilo de vida, no solo un espacio. Facilitar el proceso de solicitud.",
    "solution": "Un sitio web con tours virtuales, testimonios de residentes y un formulario de solicitud en línea detallado.",
    "services": ["Diseño y Desarrollo Web", "Tours Virtuales 360"]
  },
  {
    "id": "jazaguilar-com",
    "title": "Jaz Aguilar",
    "category": "E-commerce",
    "sector": "Sector industrial",
    "website": "https://jazaguilar.com",
    "client": "Jaz Aguilar",
    "image": getNextImage(),
    "description": "E-commerce del sector industrial.",
    "challenge": "Crear una experiencia de compra B2B eficiente.",
    "solution": "Plataforma e-commerce con funcionalidades B2B.",
    "services": ["Desarrollo de E-commerce", "UX para B2B"]
  },
  {
    "id": "elisawagnericp-com",
    "title": "Elisa Wagner ICP",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://elisawagnericp.com",
    "client": "Elisa Wagner ICP",
    "image": getNextImage(),
    "description": "Sitio de servicios profesionales.",
    "challenge": "Establecer una marca personal fuerte y profesional.",
    "solution": "Un sitio web centrado en la figura del profesional, con blog, testimonios y una clara propuesta de valor.",
    "services": ["Diseño y Desarrollo Web", "Branding Personal Digital"]
  },
  {
    "id": "arco-techos-mx",
    "title": "Arco Techos",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://arco-techos.mx",
    "client": "Arco Techos",
    "image": getNextImage(),
    "description": "Sitio para empresa de construcción de techos industriales.",
    "challenge": "Mostrar la escala y calidad de proyectos de gran envergadura.",
    "solution": "Un portafolio visual con galerías de proyectos, videos time-lapse de construcción y estudios de caso detallados.",
    "services": ["Diseño y Desarrollo Web", "Portafolio de Proyectos Industriales"]
  },
  {
    "id": "abevolks-com",
    "title": "Abe Volks",
    "category": "E-commerce",
    "sector": "Sector industrial",
    "website": "https://abevolks.com",
    "client": "Abe Volks",
    "image": getNextImage(),
    "description": "E-commerce de refacciones automotrices.",
    "challenge": "Crear un catálogo digital fácil de navegar para un nicho específico.",
    "solution": "Una tienda online con un buscador por modelo y año, y guías de instalación en video.",
    "services": ["Desarrollo de E-commerce", "Contenido de Video Técnico"]
  },
  {
    "id": "cimbrayaccesorios-com-mx",
    "title": "Cimbra y Accesorios",
    "category": "Connective",
    "sector": "Catalogo",
    "website": "https://www.cimbrayaccesorios.com.mx/",
    "client": "Cimbra y Accesorios",
    "image": getNextImage(),
    "description": "Catálogo digital de accesorios para cimbra.",
    "challenge": "Facilitar la solicitud de cotizaciones para constructoras.",
    "solution": "Un catálogo en línea donde los usuarios pueden añadir productos a una 'lista de cotización' y enviarla con un clic.",
    "services": ["Desarrollo de Catálogo Digital", "Sistema de Cotización"]
  },
  {
    "id": "puntales-com-mx",
    "title": "Puntales.com.mx",
    "category": "Connective",
    "sector": "Catalogo",
    "website": "https://www.puntales.com.mx/",
    "client": "Puntales.com.mx",
    "image": getNextImage(),
    "description": "Catálogo especializado en puntales para construcción.",
    "challenge": "Posicionarse como el experto número uno en un producto muy específico.",
    "solution": "Un sitio web de nicho con contenido técnico detallado, tablas comparativas y un blog sobre mejores prácticas de uso.",
    "services": ["Desarrollo de Catálogo Digital", "Marketing de Nicho"]
  },
  {
    "id": "puntales-mx",
    "title": "Puntales.mx",
    "category": "Connective",
    "sector": "Catalogo",
    "website": "https://www.puntales.mx/",
    "client": "Puntales.mx",
    "image": getNextImage(),
    "description": "Catálogo de puntales y andamios.",
    "challenge": "Capturar el mercado B2B de la construcción.",
    "solution": "Plataforma de catálogo con especificaciones técnicas claras y un proceso de contacto optimizado para la generación de leads B2B.",
    "services": ["Desarrollo de Catálogo Digital", "Generación de Leads B2B"]
  },
  {
    "id": "sifsa-mx",
    "title": "Sifsa",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://www.sifsa.mx/",
    "client": "Sifsa",
    "image": getNextImage(),
    "description": "Sitio de servicios profesionales.",
    "challenge": "Modernizar la imagen de una empresa establecida.",
    "solution": "Un rediseño web completo con una identidad visual renovada y contenido actualizado que refleja su liderazgo en el sector.",
    "services": ["Rediseño de Sitio Web", "Branding Digital"]
  },
  {
    "id": "voltagroup-com-mx",
    "title": "Volta Group",
    "category": "Connective",
    "sector": "Noticias",
    "website": "https://voltagroup.com.mx/",
    "client": "Volta Group",
    "image": getNextImage(),
    "description": "Portal de noticias y análisis.",
    "challenge": "Fomentar la suscripción y la lectura recurrente.",
    "solution": "Un diseño limpio enfocado en la legibilidad, con CTAs para suscripción a newsletter y contenido premium.",
    "services": ["Desarrollo de Portal de Noticias", "Estrategia de Suscripción"]
  },
  {
    "id": "grupojaia-com-mx",
    "title": "Grupo Jaia",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://grupojaia.com.mx/",
    "client": "Grupo Jaia",
    "image": getNextImage(),
    "description": "Sitio web para un grupo de servicios profesionales.",
    "challenge": "Presentar múltiples líneas de negocio de forma clara y unificada.",
    "solution": "Una arquitectura web que permite una navegación clara entre los diferentes servicios, con páginas de aterrizaje específicas para cada uno.",
    "services": ["Diseño y Desarrollo Web", "Arquitectura de la Información"]
  },
  {
    "id": "turismar-com-mx",
    "title": "Turismar",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://turismar.com.mx",
    "client": "Turismar",
    "image": getNextImage(),
    "description": "Sitio para empresa del sector industrial.",
    "challenge": "Crear una plataforma digital para una empresa tradicional.",
    "solution": "Un sitio web corporativo que digitaliza su catálogo de servicios y facilita el primer contacto con nuevos clientes.",
    "services": ["Diseño y Desarrollo Web", "Digitalización de Servicios"]
  },
  {
    "id": "hiperprint-mx",
    "title": "Hiperprint",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://hiperprint.mx",
    "client": "Hiperprint",
    "image": getNextImage(),
    "description": "Sitio para imprenta industrial.",
    "challenge": "Facilitar el proceso de cotización para trabajos de impresión complejos.",
    "solution": "Un formulario de cotización dinámico que permite a los usuarios especificar todos los detalles de su proyecto para recibir un presupuesto exacto.",
    "services": ["Diseño y Desarrollo Web", "Formularios de Cotización Avanzados"]
  },
  {
    "id": "consultorescaf-mx",
    "title": "Consultores CAF",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://consultorescaf.mx/",
    "client": "Consultores CAF",
    "image": getNextImage(),
    "description": "Sitio para consultora de servicios.",
    "challenge": "Establecer autoridad y confianza en el nicho de consultoría.",
    "solution": "Un sitio profesional con un blog de liderazgo de opinión y casos de estudio detallados.",
    "services": ["Diseño y Desarrollo Web", "Marketing de Contenidos B2B"]
  },
  {
    "id": "epidemic-mx",
    "title": "Epidemic",
    "category": "E-commerce",
    "sector": "Ropa",
    "website": "https://epidemic.mx/",
    "client": "Epidemic",
    "image": getNextImage(),
    "description": "E-commerce de moda urbana.",
    "challenge": "Conectar con una audiencia joven y crear una marca de culto.",
    "solution": "Una tienda online con una estética muy marcada, integración con Instagram Shopping y colaboraciones con influencers del streetwear.",
    "services": ["Desarrollo de E-commerce", "Marketing de Influencers"]
  },
  {
    "id": "rapidpre-mx",
    "title": "Rapid Pre",
    "category": "Connective",
    "sector": "Sector industrial",
    "website": "https://rapidpre.mx/",
    "client": "Rapid Pre",
    "image": getNextImage(),
    "description": "Sitio del sector industrial.",
    "challenge": "Mostrar la eficiencia y tecnología de la empresa.",
    "solution": "Un sitio web con videos de procesos y una sección de tecnología que destaca su ventaja competitiva.",
    "services": ["Diseño y Desarrollo Web", "Producción de Video Corporativo"]
  },
  {
    "id": "toshiba-com-mx",
    "title": "Toshiba México",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://www.toshiba.com.mx/",
    "client": "Toshiba México",
    "image": getNextImage(),
    "description": "Sitio de servicios profesionales.",
    "challenge": "Adaptar una marca global al mercado mexicano.",
    "solution": "Un sitio web que localiza el contenido y los casos de estudio para resonar con las necesidades del mercado mexicano.",
    "services": ["Diseño y Desarrollo Web", "Localización de Contenido"]
  },
  {
    "id": "meigas-es",
    "title": "Meigas",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://www.meigas.es/",
    "client": "Meigas",
    "image": getNextImage(),
    "description": "Sitio de servicios profesionales.",
    "challenge": "Crear una identidad digital única y memorable.",
    "solution": "Un diseño web con un fuerte componente de branding, utilizando una paleta de colores y tipografía distintiva.",
    "services": ["Diseño y Desarrollo Web", "Branding Digital"]
  },
  {
    "id": "lifeinsuranceexpert-ca",
    "title": "Life Insurance Expert",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://lifeinsuranceexpert.ca/",
    "client": "Life Insurance Expert",
    "image": getNextImage(),
    "description": "Sitio para experto en seguros de vida.",
    "challenge": "Simplificar un tema complejo y generar confianza.",
    "solution": "Un sitio con calculadoras interactivas, guías sencillas y un blog que responde a las preguntas más comunes de los clientes.",
    "services": ["Diseño y Desarrollo Web", "Herramientas Interactivas"]
  },
  {
    "id": "everydaygroup-ca",
    "title": "Everyday Group",
    "category": "Connective",
    "sector": "Actividades recreativas",
    "website": "https://everydaygroup.ca/",
    "client": "Everyday Group",
    "image": getNextImage(),
    "description": "Plataforma para grupo de actividades recreativas.",
    "challenge": "Ofrecer y gestionar múltiples actividades bajo una misma marca.",
    "solution": "Un portal web que permite a los usuarios explorar y reservar diferentes actividades, con perfiles para cada una.",
    "services": ["Diseño y Desarrollo Web", "Sistema de Reservas Multi-actividad"]
  },
  {
    "id": "gate48vacations-com",
    "title": "Gate 48 Vacations",
    "category": "Connective",
    "sector": "Servicios Profesionales",
    "website": "https://www.gate48vacations.com/en",
    "client": "Gate 48 Vacations",
    "image": getNextImage(),
    "description": "Sitio para agencia de viajes.",
    "challenge": "Inspirar a viajar y facilitar la reserva de paquetes.",
    "solution": "Un sitio web con imágenes y videos inspiradores de destinos, y un motor de reservas integrado.",
    "services": ["Diseño y Desarrollo Web", "Motor de Reservas de Viajes"]
  },
  {
    "id": "cucubecerra-com",
    "title": "Cucu Becerra",
    "category": "E-commerce",
    "sector": "Ropa",
    "website": "https://cucubecerra.com/",
    "client": "Cucu Becerra",
    "image": getNextImage(),
    "description": "E-commerce para marca de ropa.",
    "challenge": "Crear una experiencia de compra online que refleje la calidad de la marca.",
    "solution": "Una tienda online con un diseño limpio, fotografía de alta calidad y una experiencia de checkout optimizada.",
    "services": ["Desarrollo de E-commerce", "Optimización de la Conversión (CRO)"]
  }
];

export const portfolioCategories = Array.from(new Set(portfolioItems.map(item => item.category)));
export const portfolioSectors = Array.from(new Set(portfolioItems.map(item => item.sector)));


    